package goit.javadeveloper.note;

import org.springframework.stereotype.Service;

import java.util.Map;
import java.util.TreeMap;

@Service
public class NoteStorage {
    private Map<Long, Note> notes = new TreeMap<>();
    private long nextAutoGeneratedId = 1;

    public Map<Long, Note> getNotes() {
        return notes;
    }

    public long getNextAutoGeneratedId() {
        return nextAutoGeneratedId;
    }

    public void setNextAutoGeneratedId() {
        this.nextAutoGeneratedId++;
    }
}
